version: '3.4'

services:
  postgres-cpb:
    container_name: postgres-cpb
    image: postgres:15.1
    volumes:
      - ./src/tmp/postgres-cpb-data/:/var/lib/postgresql/pgdata
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "controle_paroquial"
    ports:
      - "5432:5432"
